name: file_builder
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ^3.2.3

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  pedantic: ^1.10.0
